package top.fusb.deploybot.config;

import lombok.RequiredArgsConstructor;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.context.event.ApplicationReadyEvent;
import org.springframework.context.event.EventListener;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.List;

/**
 * 启动后对历史 H2 表结构做兜底修正，避免 Hibernate 对旧列约束迁移不彻底。
 */
@Component
@RequiredArgsConstructor
public class SchemaMigrationBootstrap {
    private static final Logger log = LoggerFactory.getLogger(SchemaMigrationBootstrap.class);

    private final JdbcTemplate jdbcTemplate;

    @EventListener(ApplicationReadyEvent.class)
    public void migrate() {
        List<String> statements = List.of(
                "ALTER TABLE IF EXISTS deployments ALTER COLUMN status VARCHAR(255)",
                "ALTER TABLE IF EXISTS deployments ALTER COLUMN pipeline_id BIGINT NULL",
                "ALTER TABLE IF EXISTS deployments ALTER COLUMN variables_json CLOB",
                "ALTER TABLE IF EXISTS deployments ADD COLUMN IF NOT EXISTS execution_snapshot_json CLOB",
                "ALTER TABLE IF EXISTS deployments ADD COLUMN IF NOT EXISTS pipeline_name VARCHAR(255)",
                "ALTER TABLE IF EXISTS deployments ADD COLUMN IF NOT EXISTS project_name VARCHAR(255)",
                "ALTER TABLE IF EXISTS deployments ADD COLUMN IF NOT EXISTS stopped_by VARCHAR(1000)",
                "ALTER TABLE IF EXISTS deployments ADD COLUMN IF NOT EXISTS build_step_total INTEGER",
                "ALTER TABLE IF EXISTS deployments ADD COLUMN IF NOT EXISTS deploy_step_total INTEGER",
                "ALTER TABLE IF EXISTS templates ADD COLUMN IF NOT EXISTS plugin_id VARCHAR(100)",
                "ALTER TABLE IF EXISTS pipelines ALTER COLUMN template_id BIGINT NULL",
                "ALTER TABLE IF EXISTS pipelines ADD COLUMN IF NOT EXISTS template_plugin_id VARCHAR(100)",
                "ALTER TABLE IF EXISTS pipelines ADD COLUMN IF NOT EXISTS builtin_template_key VARCHAR(100)",
                "ALTER TABLE IF EXISTS pipelines ADD COLUMN IF NOT EXISTS template_name_snapshot VARCHAR(255)",
                "ALTER TABLE IF EXISTS pipelines ADD COLUMN IF NOT EXISTS template_type_snapshot VARCHAR(100)",
                "ALTER TABLE IF EXISTS pipelines ADD COLUMN IF NOT EXISTS template_monitor_process BOOLEAN DEFAULT FALSE",
                "ALTER TABLE IF EXISTS pipelines ADD COLUMN IF NOT EXISTS target_dir VARCHAR(1000)",
                "ALTER TABLE IF EXISTS pipelines ADD COLUMN IF NOT EXISTS notification_bindings_json CLOB",
                "ALTER TABLE IF EXISTS pipelines ADD COLUMN IF NOT EXISTS maven_settings_id BIGINT",
                "ALTER TABLE IF EXISTS pipelines ADD COLUMN IF NOT EXISTS locked BOOLEAN DEFAULT FALSE",
                "ALTER TABLE IF EXISTS pipelines ADD COLUMN IF NOT EXISTS lock_reason VARCHAR(1000)",
                "ALTER TABLE IF EXISTS pipelines ADD COLUMN IF NOT EXISTS lock_start_at TIMESTAMP",
                "ALTER TABLE IF EXISTS pipelines ADD COLUMN IF NOT EXISTS lock_end_at TIMESTAMP",
                "DROP INDEX IF EXISTS CONSTRAINT_INDEX_F",
                "DROP INDEX IF EXISTS UKEG3I2E4W6KIJ7JAHN7UM7ELKI_INDEX_F",
                "DROP INDEX IF EXISTS UK_PIPELINES_NAME",
                "ALTER TABLE IF EXISTS maven_settings ADD COLUMN IF NOT EXISTS runtime_environment_id BIGINT",
                "ALTER TABLE IF EXISTS maven_settings ADD COLUMN IF NOT EXISTS is_default BOOLEAN DEFAULT FALSE",
                "ALTER TABLE IF EXISTS maven_settings ADD COLUMN IF NOT EXISTS deleted BOOLEAN DEFAULT FALSE",
                "ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS avatar VARCHAR(500)",
                "ALTER TABLE IF EXISTS system_settings ADD COLUMN IF NOT EXISTS cleanup_enabled BOOLEAN",
                "ALTER TABLE IF EXISTS system_settings ADD COLUMN IF NOT EXISTS artifact_retain_success_count INTEGER",
                "ALTER TABLE IF EXISTS system_settings ADD COLUMN IF NOT EXISTS clean_runs_on_success BOOLEAN",
                "ALTER TABLE IF EXISTS system_settings ADD COLUMN IF NOT EXISTS failed_run_retain_days INTEGER",
                "ALTER TABLE IF EXISTS notification_templates ADD COLUMN IF NOT EXISTS template_mode VARCHAR(50) DEFAULT 'TEXT'",
                "ALTER TABLE IF EXISTS services ADD COLUMN IF NOT EXISTS heartbeat_miss_count INTEGER DEFAULT 0",
                "ALTER TABLE IF EXISTS services ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0",
                "CREATE TABLE IF NOT EXISTS service_pid_history (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, service_id BIGINT NOT NULL, deployment_id BIGINT, previous_pid BIGINT, current_pid BIGINT, previous_status VARCHAR(50), current_status VARCHAR(50), change_source VARCHAR(50), note VARCHAR(2000), created_at TIMESTAMP NOT NULL)",
                "CREATE UNIQUE INDEX IF NOT EXISTS uk_services_pipeline_id ON services(pipeline_id)",
                "CREATE TABLE IF NOT EXISTS user_favorite_pipelines (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT NOT NULL, pipeline_id BIGINT NOT NULL, created_at TIMESTAMP NOT NULL)",
                "CREATE UNIQUE INDEX IF NOT EXISTS uk_user_favorite_pipeline ON user_favorite_pipelines(user_id, pipeline_id)"
        );
        statements.forEach(this::executeSilently);
        dropPipelineNameUniqueConstraints();
    }

    private void dropPipelineNameUniqueConstraints() {
        findPipelineNameUniqueConstraintNames().forEach(name -> executeSilently("ALTER TABLE pipelines DROP CONSTRAINT IF EXISTS " + name));
        findPipelineNameUniqueIndexNames().forEach(name -> executeSilently("DROP INDEX IF EXISTS " + name));
    }

    private List<String> findPipelineNameUniqueConstraintNames() {
        try {
            return jdbcTemplate.queryForList("""
                    SELECT tc.CONSTRAINT_NAME
                    FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
                    JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE kcu
                      ON tc.CONSTRAINT_SCHEMA = kcu.CONSTRAINT_SCHEMA
                     AND tc.CONSTRAINT_NAME = kcu.CONSTRAINT_NAME
                     AND tc.TABLE_NAME = kcu.TABLE_NAME
                    WHERE tc.TABLE_SCHEMA = 'PUBLIC'
                      AND tc.TABLE_NAME = 'PIPELINES'
                      AND tc.CONSTRAINT_TYPE = 'UNIQUE'
                      AND kcu.COLUMN_NAME = 'NAME'
                    """, String.class);
        } catch (Exception ex) {
            log.warn("Failed to inspect pipeline name unique constraints: {}", ex.getMessage());
            return List.of();
        }
    }

    private List<String> findPipelineNameUniqueIndexNames() {
        try {
            return jdbcTemplate.query("""
                    SELECT INDEX_NAME, NON_UNIQUE, COLUMN_NAME
                    FROM INFORMATION_SCHEMA.INDEX_COLUMNS
                    WHERE TABLE_SCHEMA = 'PUBLIC'
                      AND TABLE_NAME = 'PIPELINES'
                      AND COLUMN_NAME = 'NAME'
                    """, (rs) -> {
                List<String> names = new ArrayList<>();
                while (rs.next()) {
                    String indexName = rs.getString("INDEX_NAME");
                    Boolean nonUnique = (Boolean) rs.getObject("NON_UNIQUE");
                    if (Boolean.FALSE.equals(nonUnique) && indexName != null && !indexName.isBlank()) {
                        names.add(indexName);
                    }
                }
                return names;
            });
        } catch (Exception ex) {
            log.warn("Failed to inspect pipeline name unique indexes: {}", ex.getMessage());
            return List.of();
        }
    }

    private void executeSilently(String sql) {
        try {
            jdbcTemplate.execute(sql);
            log.info("Schema migration applied: {}", sql);
        } catch (Exception ex) {
            log.warn("Schema migration skipped or failed: {} -> {}", sql, ex.getMessage());
        }
    }
}
