server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    url: jdbc:h2:file:./runtime/deploy-bot-db
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

deploybot:
  workspace-root: ./runtime
  runtime-environment-presets: classpath:runtime-environment-presets.json
  default-templates: classpath:default-templates.json
  user:
    default-password: 12345

logging:
  file:
    name: ./runtime/logs/deploy-bot-app.log
  charset:
    console: UTF-8
    file: UTF-8
  level:
    root: INFO
    top.fusb.deploybot: INFO
